language: node_js
dist: trusty
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
  - master
install:
  - echo $CXX
  - nvm install node
  - npm install -g gulp
  - npm install -g yarn
cache:
  directories:
    - node_modules
    - src/node_modules
before_script:
  - yarn restore
script: gulp release