addons:
  apt:
    packages:
    - cmake

install:
  - nvm install v7.4.0
  - npm install -g node-gyp
  - npm install -g gulp
  - npm install -g yarn
before_script:
  - yarn restore
script: gulp release